import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/components/providers";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={jetbrainsMono.variable}>
      <head>
        {process.env.NODE_ENV === "development" && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <TRPCProvider>
          <div className="min-h-screen bg-black">
  {/* TOP BORDER (full width) */}
  <div className="border-t border-zinc-800/70" />

  {/* NAVBAR ROW */}
  <div className="border-b border-zinc-800/70">
    <div className="mx-auto max-w-7xl px-4 border-x border-zinc-800/70">
      <Navbar />
    </div>
  </div>

  {/* PAGE CONTENT */}
  <div className="mx-auto max-w-7xl px-4 border-x border-zinc-800/70">
    {children}
  </div>

  {/* BOTTOM BORDER (optional, full width) */}
  <div className="border-b border-zinc-800/70" />
</div>

          </TRPCProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
